version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=expense_tracker
      - TZ=Asia/Bangkok
    volumes:
      - ./script/create_db.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - '5432:5432'

